-- PATIO
MERGE INTO PATIO t
USING (SELECT 'Pátio Central' AS NOME, 'Av. Brasil, 1000' AS ENDERECO FROM dual) s
  ON (t.NOME = s.NOME)
WHEN NOT MATCHED THEN
  INSERT (NOME, ENDERECO) VALUES (s.NOME, s.ENDERECO);

MERGE INTO PATIO t
USING (SELECT 'Pátio Secundário' AS NOME, 'Rua das Flores, 200' AS ENDERECO FROM dual) s
  ON (t.NOME = s.NOME)
WHEN NOT MATCHED THEN
  INSERT (NOME, ENDERECO) VALUES (s.NOME, s.ENDERECO);

-- OPERADOR (substitua os hashes BCrypt conforme seus valores)
MERGE INTO OPERADOR t
USING (SELECT 'Admin' AS NOME, 'admin' AS LOGIN,
              '$2a$10$0SqzzO0WTHF1JnUkNw4oAe1UvlfCmuvDwRaDnT5.sOzVJ1Ig9bt1u' AS SENHA, -- admin123 (exemplo)
              'ROLE_ADMIN' AS PAPEL, 1 AS HABILITADO FROM dual) s
  ON (t.LOGIN = s.LOGIN)
WHEN NOT MATCHED THEN
  INSERT (NOME, LOGIN, SENHA, PAPEL, HABILITADO)
  VALUES (s.NOME, s.LOGIN, s.SENHA, s.PAPEL, s.HABILITADO);

MERGE INTO OPERADOR t
USING (SELECT 'Usuário' AS NOME, 'user' AS LOGIN,
              '$2a$10$L6O5X66sPrr.iBqcsAUJ1uvtBq6ep4aHcnKKPJggIhp2wvdTBcqlS' AS SENHA, -- user123 (exemplo)
              'ROLE_USER' AS PAPEL, 1 AS HABILITADO FROM dual) s
  ON (t.LOGIN = s.LOGIN)
WHEN NOT MATCHED THEN
  INSERT (NOME, LOGIN, SENHA, PAPEL, HABILITADO)
  VALUES (s.NOME, s.LOGIN, s.SENHA, s.PAPEL, s.HABILITADO);

-- AUTOMOVEL (usa subselect para pegar o PATIO_ID de forma determinística)
MERGE INTO AUTOMOVEL t
USING (
  SELECT
    'ABC1D23' AS PLACA,
    '9BWZZZ377VT004251' AS CHASSI,
    'Moto' AS TIPO,
    'Vermelha' AS COR,
    'Setor A' AS LOCALIZACAO_NO_PATIO,
    'Entrada hoje' AS COMENTARIOS,
    (SELECT MIN(ID) FROM PATIO WHERE NOME = 'Pátio Central') AS PATIO_ID
  FROM dual
) s
ON (t.PLACA = s.PLACA)
WHEN NOT MATCHED THEN
  INSERT (PLACA, CHASSI, TIPO, COR, LOCALIZACAO_NO_PATIO, COMENTARIOS, PATIO_ID)
  VALUES (s.PLACA, s.CHASSI, s.TIPO, s.COR, s.LOCALIZACAO_NO_PATIO, s.COMENTARIOS, s.PATIO_ID);

MERGE INTO AUTOMOVEL t
USING (
  SELECT
    'DEF4G56' AS PLACA,
    '9BWZZZ377VT004252' AS CHASSI,
    'Carro' AS TIPO,
    'Preto' AS COR,
    'Setor B' AS LOCALIZACAO_NO_PATIO,
    'Revisão pendente' AS COMENTARIOS,
    (SELECT MIN(ID) FROM PATIO WHERE NOME = 'Pátio Secundário') AS PATIO_ID
  FROM dual
) s
ON (t.PLACA = s.PLACA)
WHEN NOT MATCHED THEN
  INSERT (PLACA, CHASSI, TIPO, COR, LOCALIZACAO_NO_PATIO, COMENTARIOS, PATIO_ID)
  VALUES (s.PLACA, s.CHASSI, s.TIPO, s.COR, s.LOCALIZACAO_NO_PATIO, s.COMENTARIOS, s.PATIO_ID);
